server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Esto asegura que Angular maneje las rutas internas sin tirar error 404
    location / {
        try_files $uri $uri/ /index.html;
    }
}